### PR TITLE
Fix trailing spaces in candi.sh

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by koecher** [comment]
Is there a need for this PR? Doesn’t it work on any platform with the spaces?
May you please add a comment why we should do this in your style.
PS. Those are there for a specific reason and go through the hole script.

**Comment by tjhei** [comment]
> Is there a need for this PR?

Some editors rightfully remove trailing whitespace. This makes it difficult to contribute without annoying diffs. I wouldn't mind to have this merged.

> Doesn’t it work on any platform with the spaces?

This makes no difference for the execution of the script.

**Comment by koecher** [comment]
okay. I see your point. You can merge if you like this.

**Comment by tjhei** [comment]
I think you meant to create the PR here: https://github.com/dealii/candi/pull/80 @masterleinad ?

**Comment by masterleinad** [comment]
> I think you meant to create the PR here: dealii#80 @masterleinad ?

Yes, I did at least for the others. I guess the fork and the base are kept in sync manually?

**Comment by koecher** [comment]
Yes I manually sync my base with the dealii fork. But the dealii fork should be the base, to keep things simple, please request this on dealii/candi

**Comment by masterleinad** [comment]
@tjhei was already so kind to move the PR over. :wink:

**Comment by koecher** [comment]
perfect. Thanks for that

**Pull request closed without merging**
