### PR TITLE
fix trilinos 12 & superlu bug

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
(wait with this, I still need to compile and test)

**Comment by koecher** [comment]
is it ready to merge? the diff looks good.

**Comment by tjhei** [comment]
I think it worked (at least deal.II compiled). I have no example that uses superLU though. Do you?

**Comment by koecher** [comment]
Yes I have a lot, I'll test this out after the merge.

**Pull request merged**
