### PR TITLE
disable opencascade font stuff

### PR DESCRIPTION
**Pull request by tjhei**
With this, we no longer need freetype installed to build opencascade.

### CODE REVIEW

**Comment by koecher** [comment]
Dear Timo,
are there now any system packages (e.g. for ubuntu) which must not installed now?

**Comment by tjhei** [comment]
Let me check. You were too quick with merging though. :-)

**Comment by tjhei** [comment]
I have no additional requirements for opencascade with the next PR (incoming in a minute). There used to be stuff like freetype and opengl.

**Comment by koecher** [comment]
sorry :)

**Pull request merged**
