### PR TITLE
Allow overwriting vars

### PR DESCRIPTION
**Pull request by koecher**
This PR obsoletes #19
In a bigger sense, the usage interface of candi has been reimplemented such that
    ./candi.sh
    ./candi.sh --prefix=<PREFIX_PATH> or -p=* | --PREFIX_PATH=*
    ./candi.sh --np=<PROCS> or -np=* | --procs=* | --PROCS=* | -j*
    ./candi.sh --platform=<PROJECT/platform/supported/myplatform>  or -pf=*

### CODE REVIEW

**Comment by koecher** [comment]
@Rombur & @tjhei may you test this branch for errors?

**Comment by Rombur** [comment]
It works fine for me.

**Comment by koecher** [comment]
What system(s) do you have tested?
From my side, fedora 22 is tested and RHEL 7.1 and CentOS 7.1 are outstanding.

**Comment by Rombur** [comment]
I have tested on a cluster. I can do it on Ubuntu 15 but it will have to wait tonight.

**Comment by tjhei** [comment]
I am checking ubuntu14 and will report back. 

One thing I already noticed is that the syntax is somewhat unusual compared to other linux tools. Long options are typically "--long-option value" and short "-o value" (no equal sign, one dash followed by one letter, two dashes followed by a longer name).

Also (but that is just me), I would not introduce 5 different ways to say the same thing.

**Comment by tjhei** [comment]
Tested on ubuntu14:
- setting procs and prefix works
- had to merge from mainline (p4est, etc.)
- had to switch to deal.II unstable (8.3 doesn't detect cxx11 because of a bug and that conflicts with trilinos 12)
- Bug: setting STABLE_BUILD=false now installs to <...>/deal.II/v8.3.0
- seems to be working otherwise

**Comment by koecher** [comment]
* From my experience, ubuntu 14 has problems with v8.3.0, but the current development master works fine.
* I've created a new branch, in which the current master changes and the allow overwriting comes together
* A message regarding ubuntu 14 was added a couple of hours back
* The bug comes from a change I've done... I'll fix this
Thx for testing

**Comment by koecher** [comment]
Regarding " "--long-option value" and short "-o value" (no equal sign, one dash followed by one letter, two dashes followed by a longer name)."
Indeed this is, but it is much harder to parse them in such a way.

Introducing 5 ways for setting the PROCS is due to the fact, that I'm very unsure which is the most userfriendly way to do here.
* "--PROCS=<N>" is quite long, but matching with the variable 
* "-j<N>" is similar to make and
* "-np=<N>" or "--np=<N>" are similiar to mpirun's.

I'll think I will ship the -j<N> and the --PROCS=<N> in the final version.

**Comment by Rombur** [comment]
It works on Ubuntu 15.

**Pull request merged**
