### PR TITLE
Fixed a problem with tar permissions and ubuntu12 automake

### PR DESCRIPTION
**Pull request by mraveri**
I had a problem when installing everything in a folder where I had permissions but was not owned. In particular Trilinos tar was not expanding due to an error (Cannot utime).

This can be fixed by adding the m option (--touch) to tar. This however resulted in a problem with p4est that started checking the autoconf and automake version, failing on ubuntu12.
To solve this I added the two packages and added them to ubuntu12 requirements.

This now works on ubuntu 12 but I didn't manage to check wether the m option was creating problems on other platforms.

### CODE REVIEW

**Comment by tjhei** [comment]
> I had a problem when installing everything in a folder where I had permissions but was not owned. In particular Trilinos tar was not expanding due to an error (Cannot utime).

I would assume you will run into many other problems if you are trying to extract/compile/install into a folder where you are lacking permissions, so this fix doesn't really sound like a fix. I can imagine build steps requiring utime for example.

> This however resulted in a problem with p4est that started checking the autoconf and automake version,

I assume this is because it wants to rerun autoconf because the file dates are now wrong? I don't like the idea of installing and rerunning autoconf for everyone because of this. This pulls in a lot of stuff.

**Comment by mraveri** [comment]
Well, after changing these two things the build seems working (compiles up to deal without errors) even if I didn't run all the test of deal but just a few.

The original problem should not be really a permission problem as all permissions are in place and is just raised by tar when changing the time stamp of some files in trilinos.

The context is that I'm trying to install everything on an external HD formatted as Mac OS extended (journaled). I agree with you that the solution seems sub-optimal (and probably not worth the pain). Will try a couple of others! In the meantime if you have some ideas on how to solve this issue please let me know!

**Comment by tjhei** [comment]
How about downloading/unpacking/compiling in a local directory and just pointing the ``INSTALL_PATH`` to the external drive?

**Comment by mraveri** [comment]
Ah yes, this seems to work well! I liked having everything in just one place but this is neater.

**Comment by mraveri** [comment]
Btw, I am going to put in some other packages related to a project that I'm doing. These include doxygen, sundials, deal2lkit and pi-DoMUS just let me know if you want some of them in the main repo and I'll open appropriate PR.

**Comment by koecher** [comment]
Okay, I see it as Timo did. You already closed this PR.
The other thing: doxygen should be available on all platforms by the distribution (but not sure if MacOS have it). The others are unknown to me. But if you like you could open a PR for each seperately where you put in the packages files. Then we can discuss this in an appropriate way.

**Pull request closed without merging**
