### PR TITLE
add patch for parmetis with intel

### PR DESCRIPTION
**Pull request by tjhei**
We need -fPIC at least on the palmetto cluster at Clemson.

### CODE REVIEW

**Comment by tjhei** [comment]
@Rombur is that working for you with/without this patch?

**Comment by Rombur** [comment]
This does not work for me with or without the patch. I'm investigating, I'll report back.

**Comment by tjhei** [comment]
I think we also need Trilinos 11, because the cxx11 test in 8.3 also fails with intel for me...

**Comment by Rombur** [comment]
OK I hit this dumb error: https://bitbucket.org/fenics-project/dolfin/issues/375/intel-compiler-does-not-accept-some-c-11 Parmetis compiled with the patch.

**Comment by koecher** [comment]
Hmpf. For at least a very current intel compiler the build was successful (I now have the option of building deal.II with candi using an intel mpi-compiler-suite, but I'll redo the build with the current master branch of candi firstly and report the intel compiler version which should work without patching parmetis).

@Rombur  thanks for your latest info.

**Comment by Rombur** [comment]
I retried to compile parmetis without the patch and it works. Trilinos 12 works fine too. I am using Intel-2015.3.187

**Comment by tjhei** [comment]
I was using 
```
$ icpc --version
icpc (ICC) 15.0.0 20140723
```
did you use FC=mpiifort and FF=mpiifort?

**Comment by Rombur** [comment]
@tjhei yes, I did.

**Comment by tjhei** [comment]
I think I forgot to set the compilers correctly because now I can't even compile PETSc with mpiicc. Sigh.

**Comment by tjhei** [comment]
I am currently struggling with the fact that trilinos is picking up the wrong compilers (mpicxx instead of mpiicpc). I wonder if trilinos.package should get something like
```
--- a/deal.II/packages/trilinos.package
+++ b/deal.II/packages/trilinos.package
@@ -50,6 +50,9 @@ fi
 #########################################################################
 
 CONFOPTS="${TRILINOS_CONFOPTS} \
+-D CMAKE_C_COMPILER=$CC \
+-D CMAKE_CXX_COMPILER=$CXX     \
+-D CMAKE_Fortran_COMPILER=$FC \
```
? (and I no longer need the change to parmetis I suggested earlier now that I am picking up the correct compilers)

**Comment by koecher** [comment]
So far, this was not needed. But we can include these options since candi is warning the user if $CC, $CXX and $FC are not set up. Or even better, we include these if $CC, $CXX and/or $FC are set to something which is not empty.

**Comment by koecher** [comment]
@tjhei your idea, some code cleanups and an additional fix for parmetis within trilinos can be found here: PR #45

**Comment by koecher** [comment]
This PR can be closed. A somehow unrelated patch is given by PR #45.

**Pull request closed without merging**
