### PR TITLE
set sane module path

### PR DESCRIPTION
**Pull request by tjhei**
I don't quite understand the old logic for the module path. I had set a different install path than the prefix path (to keep the installation clean) and the module path ended up being
```
/ssd/candi-8.4-testing/deal.II-v8.4.0-rc2/share/modulefiles/ssd/candi-8.4-testing/deal.II-v8.4.0-rc2/default
```
With this patch it will be at
```
/ssd/candi-8.4-testing/deal.II-v8.4.0-rc2/share/modulefiles/default
```
I think the new logic is always correct, because deal.II will put a ``share`` folder under the install path.

### CODE REVIEW

**Comment by koecher** [comment]
Sorry. I did not find the time to correct the modulefile pathes so far. In the old version I included a so far non existent variable for the compiler.

**Comment by koecher** [comment]
I think we should use the new variable `CONFIGURATION_PATH=${PREFIX_PATH}/${PROJECT}/share/configuration` also for the modulefiles.
All other packages may have to be checked also.

**Comment by tjhei** [comment]
I don't see any other place where modules are mentioned. Is each package supposed to create a module? I don't have module support installed so I can not test it here.

**Comment by koecher** [comment]
Yes, each package is supposed to a have its own modulefile (same as for the configuration files), this is due to the new structure of having each package in a seperate subfolder (the `DEAL_II_DIR` does not hold all header files anymore). At least for trilinos I will need one in the near future.
But the question was intended to use
`MODULEFILE_PATH=${CONFIGURATION_PATH}/modulefiles`
instead of
`MODULEFILE_PATH=${INSTALL_PATH}/share/modulefiles`

**Comment by tjhei** [comment]
okay, makes sense. Like this?

**Comment by koecher** [comment]
perfect & thank you very much

**Pull request merged**
