### PR TITLE
trilinos 12.6.1

### PR DESCRIPTION
**Pull request by tjhei**
Compilation works, but 12.6.1 is not rigorously tested with deal.II yet. @koecher, should we wait with this PR?

### CODE REVIEW

**Comment by koecher** [comment]
yes I think so

**Comment by koecher** [comment]
@tjhei Timo do you think it is safe to merge?

**Comment by tjhei** [comment]
I don't think we have run the full testsuite with 12.6.1 yet. I think we stick to 12.4 for the 8.4 release as recommended, so I wouldn't mind waiting until that is done.

**Comment by koecher** [comment]
Kind reminder: @tjhei 
Unfortunately, I did not tested this trilinos version so far.
The last post is one month ago and deal.II v8.4.0 is released. Do you have secured tests running on this version? candi is recently released to version v0.8.4 (which does not include this patch), so we could merge more safely.
I would like to firstly merge this new trilinos release before working on the outstanding superlu version integration.

**Pull request closed without merging**
