### PR TITLE
Add suppport for a standard linux system.

### PR DESCRIPTION
**Pull request by Rombur**
The goal is to install deal.ii on a linux machine that as the minimum number of libraries already installed. There are two more things that I would like to do but I need some pointers:
1) installing everything takes for ever, it would be nice if it could be piloted from candi.cfg
2) I would like to use candi on Intel clusters, so I need a way to give the path and the name of BLAS and Lapack libraries.

### CODE REVIEW

**Comment by koecher** [comment]
Hi Bruno,

firstly, your pull request looks good,
but may you update the checksum variable for the newer boost by using the gnu/linux tool md5sum on a correctly downloaded boost file (1.58).
This is very useful for the case if the download was non-correct (e.g. a previous aborted run of candi).

I have a problem with "a standart linux" machine, candi is coming from dorsal (a furthermore non-supported) bash installer for FEniCS; I face the same problems - there is no standart linux machine,
and thus I used the same structure.
The problem for a starting user is, that he don't know which libraries on his machine must be installed before the installer will run without any trouble.

I may not understand (1) of your appointment correctly.
If you would like to pass down variables from the top-level you can define a bash-variable similar to the "DEAL_CONFOPTS". This variable should be available in the whole progress.

If I would like to install something permant, I like to use the candi infrastructure for installing a new "project", see for example the other project folders and the use of the script "./switch-project-to <X>".

For the (2) question, as before, you can define bash-variables on the front-level cfg-file and use them in the dependent package file.

**Comment by Rombur** [comment]
I have added the checksum for boost.

Standard linux was a badly chosen name. This Linux platform is for clusters where the user doesn't have access to a package manager. For example, I'm working on a cluster that has centos 6.5 but some packages are missing. I can't simply use the package manager to install them. So, I want something that only requires packages that have to be installed on a cluster (mpi, lapack, blas, etc).

For (1) what I mean is this: if I turn petsc and hdf5 off, I don't want them to be downloaded or installed at all. Right now, DEAL_CONFOPTS is just used to configure deal.II but if I don't want to use petsc with deal.ii there is no reason to install petsc. If later on, I decide that I want petsc then candi can install it.

**Comment by koecher** [comment]
Another thing, it would be more nice when you prepare a patch file by using
"diff -u -r -N bzip2-1.0.6-origin bzip2-1.0.6 > bzip2-1.0.6.patch"
instead of copying your changes into the package file.
I see that you have deleted the line CC=gcc, but you do not include something from the runtime variables of candi, thus the patch would be enough.

See for instance the sub-folder deal.II/patches and the package file of SuperLU how to apply the
patch file after the download, e.g.:
patch -p1 --forward < ${ORIG_DIR}/${PROJECT}/patches/SuperLU_DIST_3.3.patch || true

I had (but currently do not have anymore) some RedHat/CentOS 6 systems also with the same problem.
Maybe we should use another name. Let's say linuxclustersuite or something in that way.
Does it make sense to compile the usual infrastruction within another "project"?

For newer gcc and mpi compilers use the candi-projects gcc and afterwards mpi.

Regarding (1): Ah, this is something I would love to have, but unfortunately I did not find the time to tweak candi in that way so far. Patches are welcome ;-)

**Comment by Rombur** [comment]
I changed the name of the platform to linux_cluster and I use a patch to change the Makefile.

> Does it make sense to compile the usual infrastruction within another "project"?
I think that it's better if people use their package manager as much as possible so I don't see the point right now. Unless another code needs the same libraries.

**Comment by koecher** [comment]
Thanks for your update, I'll look for your changes in detail next week.
Kind regards
  Uwe

**Pull request merged**
