### PR TITLE
Repo path

### PR DESCRIPTION
**Pull request by Rombur**
This changes the layout when deal.II is installed. All the libraries but deal.II are installed in the libs folder (feel free to change if you have a better name). Moreover, when it is possible, install the libraries in their own subdirectory (similar to what is already done for PETSc and p4est). Also fix a bug where ```METIS_DIR``` was never exported.

### CODE REVIEW

**Comment by koecher** [comment]
This is something I have thought about a longer time ago. Having the optional packages within a their folder is nice from the point of view of deleting them, and reinstall with e.g. a newer version without reinstalling everything. (I would call the folder `opt` since any `lib` is usually used only for static and dynamic libraries).

The point which I faced to not providing something like this was, that the `include` directory of `DEAL_II_DIR` will than not having the headers of the sub-packages. I'll think I can fix my bash script for setting up my used IDE for that case.

Let me test your approach next week (please remind me if I forget in 2 weeks).

**Comment by tjhei** [comment]
Nice! Awesome for working on that. :+1: 

I think you can also safely move hdf5 to a subdirectory.

**Comment by koecher** [comment]
Of course, every installed dependency should get its own dir.
But before we do that, I think we need to restructure the package ON/OFF switching policies by explicitly setting them in the configuration file (and not rebuilding it from `DEAL_CONFOPTS`) to make it more clear for the users of candi...

**Comment by tjhei** [comment]
> But before we do that, I think we need to restructure the package ON/OFF switching policies

I think this PR also makes sense independently of that.

Regarding the restructuring: fundamentally this is a problem of tracking optional and required dependencies and what is already installed. To be most generic, you would basically need to implement a package manager. I think we are trying to avoid that. :-)

I would create a variable in candi.cfg that lists the libs to install. I would then query each package in that list if they want to add additional packages to that list (required dependencies). The order of installation is important too, so shouldn't depend on the order the user puts it in. Finally, the platform can add things also.

The interface for the user could be something like
```
INSTALL="dealii"

# uncomment to get something more complete:
#INSTALL="$INSTALL trilinos petsc p4est"

#uncomment to get everything:
#INSTALL="$INSTALL slepc hdf5 superlu"
```

Things to figure out:
- need to recompile stuff if we install an optional dependency? Detect automatically?
- who determines installation order?
- should the user still be allowed to do "./candi install-package superlu"?
- how to detect if projects are already installed?

**Comment by tjhei** [comment]
@Rombur Working fine on ubuntu14 here. Trilinos is also not in a subdirectory yet.

**Comment by Rombur** [comment]
@tjhei Thanks, it should be fixed.

**Comment by koecher** [comment]
@tjhei indeed we had discussions together with Matthias how to deal on user specific needs and how to bundle them at the PDESoft 2014...

Also, this awesome contribution is independent of that discussion, but regarding our candi.sh package management, we install e.g. a newer cmake for ubuntu12. This is fine by the way, but we need to provide a `source` able configuration file or a `modulefile` to make the user environment working after the perfect run of candi. Thus I think, we firstly have to be clear which packages we need to install regarding the request of the user, and then check if this is useful for the platform.

Thereby, we should abort if a non-working option set is done by the user and write documentation on which (tested to work) combinations should work. Since we do not have infinite time on dealing with that, we need to restrict for combinations which are mostly used for the tutorial programs of deal.II...

**Pull request merged**
