### PR TITLE
add opencascade

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
Do you prefer cloning from github or a tarball? (the git repo is quite big and I got annoyed how long the clone took so I switched to a tarball)

**Comment by tjhei** [comment]
Do you prefer git clone or tarballs? I got tired of waiting for the clone to finish (big repo), so I switched to a tarball download (both are in the file).

Do I have to add "once:opencascade" to every platform?

**Comment by koecher** [comment]
I prefer tarballs if possible, since there are usually smaller and faster for downloads.
Do I have to add "once:opencascade" to every platform?
Unfortunately yes. Maybe we need to tweak the on/off feature from @Rombur for opencascade

**Comment by tjhei** [comment]
Okay, added references to opencascade to the projects.

**Comment by Rombur** [comment]
ping?

**Comment by koecher** [comment]
Sry, I'm very in a new research, so that I did not have tested this branch so far. But I think there is a missing command in the DEAL_II_CONFOPTS for opencascade

**Comment by tjhei** [comment]
I am installing directly into ```${INSTALL_PATH}``` so deal.II picks it up automatically. Want me to put it into a subdirectory instead?

**Comment by koecher** [comment]
Ah okay, but then we need something to switch off the build of opencascase. (add opencascade to PACKAGES_OFF somehow)

**Comment by tjhei** [comment]
Oh, I didn't know that you use parse DEAL_CONFOPTS in candi.cfg to skip installing packages. That means that I can not skip installing Trilinos and configure deal.II to pick up a Trilinos version I have  installed somewhere else?

**Comment by Rombur** [comment]
That's right. If you provide your own version of Trilinos, candi will still install Trilinos but then, it won't use it. I know how to fix this, I just have to find the time to do it.

**Comment by tjhei** [comment]
I would find it more intuitive to list all packages in the .cfg that you want installed (so you can remove/comment out the ones you don't want) and the deal.II installation will get the hints of every installed package (basically every installed package can set env variables like TRILINOS_DIR if needed).

**Comment by koecher** [comment]
Okay, for now, adding  -DDEAL_II_WITH_OPENCASCADE=OFF to your PR would be enough.
Afterwards, I think I can merge this branch into master.

**Comment by tjhei** [comment]
okay, done. What is your policy on disabling packages by default? It looks like all other dependencies are on by default.

(my preference would be to define sensible defaults for minimal/default/everything, where default is enough to run all tutorial steps but exclude hdf5, netcdf, superlu, parmetis for example)

**Comment by Rombur** [comment]
Right now, everything is turned on by default. The problem with having something off by default is that people don't read error messages and you get things like this https://groups.google.com/forum/#!searchin/dealii/candi/dealii/FFeL9YVXe1A/5PON22SZOnIJ (error message: "ExcMETISNotInstalled()" yet Weixiong blames the problem on umfpack) By turning everything on by default, we avoid that kind of stuff.

**Comment by tjhei** [comment]
So you would also prefer opencascase=on?

**Comment by Rombur** [comment]
I don't have an opinion on this. I think that it makes sense for opencascade to be off by default because not many people will need it but I can already see the mails on the mailing list about the bugs in candi.

**Comment by koecher** [comment]
I think opencascade could be kept off by default.

**Comment by tjhei** [comment]
done

**Comment by koecher** [comment]
Perfect. Thank you very much for this feature!

**Pull request merged**
