### PR TITLE
allow mirror URLs and improve tarball hashing

### PR DESCRIPTION
**Pull request by tjhei**
- packages can overwrite download urls by using the format URLS="url1
url2 url3"
- this allows us to specify alternate download locations and filenames
- the download_file() function now robustly checks downloads
before/after downloading

### CODE REVIEW

**Comment by koecher** [comment]
Looks very nicely. But I need to check this in a major check firstly.
Thank you Timo.

**Comment by koecher** [comment]
@tjhei I have decided in not wasting your time. The reference above implements the first part of your idea. The second part (mirrors) is coming soon.

**Comment by tjhei** [comment]
No problem! I should have noted that this was WIP and I was hoping you would take it from here. ;-)

The reason I put the URL into the .package had several reasons:
1. Allow setting mirrors especially for projects where there is more than one download location (I was not planning to host everything @clemson, but I guess I could if you want -- didn't think about it).
2. I had an issue earlier with opencascade, where the .tar.gz of the release has a different name than the folder that comes out of it (see https://github.com/tpaviot/oce/archive/OCE-0.17.zip), so I had to download, rename, upload to my own github. With URLS I could just specify a different download URL.
3. I think it is more intuitive to specify the URL instead of individual parts that are then stitched together.

**Comment by koecher** [comment]
Regarding: "No problem! I should have noted that this was WIP and I was hoping you would take it from here. ;-)"
Perfect. I had some head-banging because of using your ideas as a starting point without using your commits :-)

For 2) There is an undocumented variable EXTRACTSTO (unsure if this is the correct name), which can be further set if a problem you have denoted occures...

For 1) Indeed, having the opportunity of mirror URLs is inherently needed (at least for trilinos, since the default is very slow...). As written, this will be the next patch I'll write.

For 3) Having URL(s) in one description breaks the current interface, adding addional MIRRORS don't.
Please remind that candi was tweaked by mine to have something like a general linux installer for projects.

Anyhow, I have some more ideas of cleaning up some dorsal-origin restrictions for the "v1.0.0" release of candi. Currently I try to merge only the very necessary patches for the next v0.6 tagging.
Afterwards, more deeper changes will be applied to get rid of some restrictions.

**Comment by tjhei** [comment]
> For 3) Having URL(s) in one description breaks the current interface, adding addional MIRRORS don't.
Please remind that candi was tweaked by mine to have something like a general linux installer for projects.

It does not break the old recipes. If you look at my code you will see that I am setting URLS to ```${SOURCE}${NAME}${PACKING}``` if you don't specify it in a recipe.

**Pull request closed without merging**
