### PR TITLE
improve command line parsing

### PR DESCRIPTION
**Pull request by tjhei**
- handle -j<space>X and -jX
- help text with -h
- better error checking

### CODE REVIEW

**Comment by tjhei** [comment]
A minor thing but I keep making that mistake. Do you want me to change the other parameters too? Maybe only accept something like "-s bla" with space but "--longer=bla"?

**Comment by koecher** [comment]
I did not want to have this behaviour. The idea was to do it as for make, hereby no whitespace is allowed for -j.
Maybe as an additional switch (-j <N> and -j<N>) are allowed).
The same for the equality ./configure --prefix=<path> (with =) is the default I know. A patch for the usage without = as additional option would be accepted.

**Comment by tjhei** [comment]
> The idea was to do it as for make, hereby no whitespace is allowed for -j.

Make supports ``-j X`` or ``--jobs=X``, see http://linux.die.net/man/1/make for example. This seems to be the standard behavior for linux tools (short options with one dash and a space vs long options with two dashes and ``=``).

**Comment by koecher** [comment]
Oh dear this seem to be new (precisely this is new to me). Anyhow, lets keep -j<N> and add -j <N> .
If you like you can remove the = for the short -p <path>, otherwise I'll look for it next week.

**Comment by koecher** [comment]
Okay, looks good so far. but we should additionally test if the shifted argument is a number and the documentation (readme.md) must be updated.

**Comment by tjhei** [comment]
like this?

**Comment by koecher** [comment]
very nice. thank you. is that ready to merge?

**Comment by tjhei** [comment]
I think it is ready, unless you are okay with getting rid of ``-pf=<bla>``.

**Comment by koecher** [comment]
That's okay. Only a few people are using this for special platforms (like general linux cluster) and it is documented so far. Thank you a lot for working that out.

**Pull request merged**
