### PR TITLE
Cleanups for dealii

### PR DESCRIPTION
**Pull request by koecher**
For further deal.II specific developments, everything which is not needed is removed with that PR.

### CODE REVIEW

**Comment by koecher** [comment]
@Rombur @tjhei as starting point for a new era, the latest candi was tagged as v0.7 and this PR cleans up everything which is not needed for deal.II

**Comment by tjhei** [comment]
I think the license file should stay in the repo.

**Comment by koecher** [comment]
The license file is still there (file LICENSE for the GNU Lesser v3), I only removed the dorsal license information details.

**Comment by tjhei** [comment]
Oh, okay. There are still two remaining outdated files: README.md.dorsal and USAGE

**Comment by koecher** [comment]
This is because, I want to merge some final things from them into their final destination...
There are also some FEniCS specific things in the candi.sh.
I'll further merge this and the PR #47 together and test this. Thus, it might be possible that the current master will not work for some time the next days.

**Pull request merged**
