### PR TITLE
Update deal.II and Trilinos. Turn MueLu ON.

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Comment by koecher** [comment]
Hi Bruno, I already have majorly updated candi for deal.II 8.3 today,
but it is not merged so far, I need to repair the Amesos2 interface for
SuperLU tomorrow. See:
https://github.com/koecher/candi/tree/dealii8.3-trilinos12-SuperLU41
May you check this first and send me pull requests on this branch if anything is not working?
Thank you.

**Comment by Rombur** [comment]
SuperLU_dist 4.1 does not compile for me. I will look into it tonight

**Comment by Rombur** [comment]
Trilinos 12.2 just came up today so maybe it is worth to jump to Trilinos 12.2 right away.

**Comment by koecher** [comment]
Okay, I'll give it a try tomorrow.
On the given branch, there are several new commits to make the current petsc & slepsc going to work.
Did you find out what is going wrong with SuperLU?

**Comment by Rombur** [comment]
So I found one problem with SuperLU. SuperLU_dist 4 does not follow the C99 standard which is used by default in gcc 4.8.2 Adding the flag -std=c99 fixes that error. I have another error but I will look into it tomorrow.

deal.II 8.3 does not support mumps anymore so the flag should be taken off from the configuration file.

Why do you force the C++11 and C++14 flags? They should be picked up by cmake. If they are not, it's a bug in deal.II

**Comment by koecher** [comment]
Forcing C++11 and disabling C++14 is a result for using clang 3.5. The debug is not fully implemented so far but it is feature complete C++14, which results in a compilation error for the bundled boost of deal.II. I'll set up a bug report for deal.II soon.

**Comment by koecher** [comment]
For SuperLU I have introduced an error for gcc (regarding a static function in xscatter). I'll fix this.

**Comment by Rombur** [comment]
The branch works for me :-)

**Comment by koecher** [comment]
Perfect. Today I'm testing it for the current opensuse an then I'll merge it into master

**Comment by koecher** [comment]
Changes are obsolete now. PR #12

**Pull request closed without merging**
